# Generated by Django 5.0.6 on 2024-06-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivarity',
            old_name='types',
            new_name='type',
        ),
    ]
